FROM python:3.11-slim

# ffmpeg install
RUN apt-get update && apt-get install -y ffmpeg

WORKDIR /app

COPY . .

RUN pip install -r requirements.txt

CMD ["sh", "-c", "gunicorn --bind 0.0.0.0:$PORT app:app"]
